variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildConfiguration
  value: Release
- name: BuildPlatform
  value: 'Any CPU'
  
pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'
  demands:
  - msbuild
  - visualstudio
  - vstest

resources:
  repositories:
  - repository: Rubeus
    type: github
    endpoint: hackbuildrepeat
    name: GhostPack/Rubeus
  - repository: SharpView 
    type: github
    endpoint: hackbuildrepeat
    name: tevora-threat/SharpView

trigger:
- main

steps:
- checkout: Rubeus
- checkout: SharpView

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: $(BuildParameters.solution)

- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'
- task: PowerShell@2
  displayName: PowerShell Script for InvisibilityCloak
  inputs:
    targetType: inline
    script: |
      wget https://raw.githubusercontent.com/xforcered/InvisibilityCloak/main/InvisibilityCloak.py -o InvisibilityCloak.py
      wget https://raw.githubusercontent.com/hackbuildrepeat/compiled_binaries/master/random-words.py -o words.py

      pip3 install requests
      pip3 install random

      $folders = Get-ChildItem -Path ".\" -directory
      foreach ($f in $folders) {$pos = $(python.exe .\words.py); python.exe .\InvisibilityCloak.py -d $f.FullName -n $pos -m reverse; echo "$f is now $pos" >> .\correlation.txt}

      gc .\correlation.txt

- task: PowerShell@2
  displayName: PowerShell Script for SharpView
  inputs:
    targetType: inline
    script: |
      Set-Content D:\a\1\s\SharpView\FodyWeavers.xml '<?xml version="1.0" encoding="utf-8" ?>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '<Weavers>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '<Costura>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml 'DisableCleanup="true"'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '<IncludeAssemblies>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml 'CommandLine'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '</IncludeAssemblies>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '</Costura>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '</Weavers>'
- task: VSBuild@1
  displayName: Build solution **\*.sln
  inputs:
    solution: $(BuildParameters.solution)
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
- task: VSTest@2
  displayName: VsTest - testAssemblies
  inputs:
    testAssemblyVer2: >-
      **\$(BuildConfiguration)\*test*.dll
       !**\obj\**
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
- task: PublishSymbols@2
  displayName: Publish symbols path
  continueOnError: True
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
    SymbolServerType: TeamServices
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: $(build.artifactstagingdirectory)

- task: PowerShell@2
  displayName: PowerShell Script for ConfuserEx
  inputs:
    targetType: inline
    script: |
      # make the confused folder
      mkdir D:\a\1\a\Confused\

      # download specific ConfuserEx version
      wget https://github.com/mkaring/ConfuserEx/releases/download/v1.6.0/ConfuserEx-CLI.zip -o ConfuserEx-CLI.zip
      Expand-Archive .\ConfuserEx-CLI.zip D:\a\1\a\

      # copy dependencies

      $sv = "D:\a\1\a\SharpView\*\bin\Release\*.exe"
      $svf = (ls $sv).Name
      $svy = ($svf -split ".exe")[0]
      cp D:\a\1\s\SharpView\packages\PCRE.NET.0.7.0\lib\net45\PCRE.NET.dll D:\a\1\a\SharpView\$svy\bin\Release\PCRE.NET.dll

      # renamed binaries

      $rb = "D:\a\1\a\Rubeus\*\bin\Release\*.exe"
      $rbf = (ls $rb).Name
      $rby = ($rbf -split ".exe")[0]

      # create confuser crpoj file
      New-Item D:\a\1\a\conf.crproj
      Set-Content D:\a\1\a\conf.crproj '<?xml version="1.0" encoding="utf-8"?>'
      Add-Content D:\a\1\a\conf.crproj '<project outputDir="D:\a\1\a\Confused\" baseDir="D:\a\1\a\" xmlns="http://confuser.codeplex.com">'
      Add-Content D:\a\1\a\conf.crproj '<rule preset="maximum" pattern="true">'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti debug" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti dump" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti ildasm" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="constants" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="ctrl flow" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="harden" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="invalid metadata" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="ref proxy" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="rename" >'
      Add-Content D:\a\1\a\conf.crproj '<argument name = "mode" value = "letters" />'
      Add-Content D:\a\1\a\conf.crproj '<argument name = "renPublic" value = "false" />'
      Add-Content D:\a\1\a\conf.crproj '<argument name = "renEnum" value = "true" />'
      Add-Content D:\a\1\a\conf.crproj '<argument name = "renameArgs" value = "false" />'
      Add-Content D:\a\1\a\conf.crproj '</protection >'
      Add-Content D:\a\1\a\conf.crproj '<protection id="watermark" action="remove" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="resources" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="typescramble" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="watermark" action="remove" />'
      Add-Content D:\a\1\a\conf.crproj '</rule>'
      Add-Content D:\a\1\a\conf.crproj "<module path='D:\a\1\a\SharpView\$svy\bin\Release\$svf' />"
      Add-Content D:\a\1\a\conf.crproj "<module path='D:\a\1\a\Rubeus\$rby\bin\Release\$rbf' />"
      Add-Content D:\a\1\a\conf.crproj "</project>"

      # execute confuser on everything
      D:\a\1\a\Confuser.CLI.exe D:\a\1\a\conf.crproj -n
      cp D:\a\1\s\correlation.txt D:\a\1\a\Confused\correlation.txt

- task: PowerShell@2
  displayName: PowerShell Script for Confused EXEs
  inputs:
    targetType: inline
    script: |
      mkdir $(Pipeline.Workspace)\a\Output\
      gci -recurse *.exe -Path $(Pipeline.Workspace)\a\Confused\| Move-Item -Destination $(Pipeline.Workspace)\a\Output\
      gci -recurse *.txt -Path $(Pipeline.Workspace)\a\Confused\| Move-Item -Destination $(Pipeline.Workspace)\a\Output\
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)\Output\
    publishLocation: 'Container'